apiVersion: apps/v1
kind: Deployment
metadata:
  name: albums-backend
  labels:
    app: {{ .Chart.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  selector:
    matchLabels:
      app: albums-backend
  template:
    metadata:
      name: albums-backend
      labels:
        app: albums-backend
    spec:
      initContainers:
        - name: wait-for-neo4j
          image: groundnuty/k8s-wait-for
          args:
            - "pod"
            - "-lapp=albums-neo4j-db"
      containers:
        - name: albums-backend
          image: "albums-backend:latest"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "{{- join " " .Values.backend.javaOptions }}"
          envFrom:
            - configMapRef:
                name: backend-configmap
          resources:
            requests:
              cpu: {{ .Values.backend.resources.cpu }}
              memory: {{ .Values.backend.resources.memory }}
            limits:
              cpu: {{ .Values.backend.resources.cpu }}
              memory: {{ .Values.backend.resources.memory }}
          readinessProbe:
            httpGet:
              path: /api/actuator/health
              port: 8080
            periodSeconds: 10
            timeoutSeconds: 30
            successThreshold: 1
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: /api/actuator/health
              port: 8080
            periodSeconds: 10
            timeoutSeconds: 5
          volumeMounts:
            - mountPath: "/data/thumbnails"
              name: thumbnail-data
            - mountPath: "/data/pictures"
              name: picture-data
      volumes:
        - name: thumbnail-data
          hostPath:
            path: {{ .Values.hostVolumePaths.thumbnails }}
            type: DirectoryOrCreate
        - name: picture-data
          hostPath:
            path: {{ .Values.hostVolumePaths.pictures }}
            type: DirectoryOrCreate