apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-configmap
  labels:
    app: {{ .Chart.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  PUBLIC_ORIGIN: {{ .Values.hostnames.app }}
  NEO4J_DB_URI: "neo4j://albums-neo4j-db:7687"
  NEO4J_DB_NAME: "{{ .Values.neo4j.credentials.dbName }}"
  NEO4J_DB_USERNAME: "{{ .Values.neo4j.credentials.username }}"
  NEO4J_DB_PASSWORD: "{{ .Values.neo4j.credentials.password }}"
  HASH_SAMPLE_SIZE: "100"
  SIMILARITY_THRESHOLD: "0.82"
  THUMNAIL_SIZE: "250"
  THUMBNAILS_DIRECTORY: "/data/thumbnails"
  FULL_IMAGE_DIRECTORY: "/data/pictures"
  RATE_LIMIT_IMAGE_UPLOAD_LIMIT: "20"
  RATE_LIMIT_IMAGE_UPLOAD_REFILL_TIME_MS: "2000"