apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-configmap
data:
  NEO4J_DB_URI: "neo4j://albums-neo4j-db:7687"
  NEO4J_DB_NAME: "{{ .Values.neo4j.dbName }}"
  NEO4J_DB_USERNAME: "{{ .Values.neo4j.username }}"
  NEO4J_DB_PASSWORD: "{{ .Values.neo4j.password }}"
  HASH_SAMPLE_SIZE: "100"
  SIMILARITY_THRESHOLD: "0.82"
  THUMNAIL_SIZE: "250"
  THUMBNAILS_DIRECTORY: "/data/thumbnails"
  FULL_IMAGE_DIRECTORY: "/data/pictures"