apiVersion: apps/v1
kind: Deployment
metadata:
  name: albums-frontend
  labels:
    app: albums-frontend
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: albums-frontend
  template:
    metadata:
      name: albums-frontend
      labels:
        app: albums-frontend
    spec:
      containers:
        - name: albums-frontend
          image: "albums-frontend:latest"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: {{ .Values.frontend.resources.cpu }}
              memory: {{ .Values.frontend.resources.memory }}
          readinessProbe:
            httpGet:
              path: /
              port: 80
            periodSeconds: 10
            timeoutSeconds: 30
            successThreshold: 1
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
            periodSeconds: 30
            timeoutSeconds: 20