apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: albums
  labels:
    app: {{ .Chart.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    - host: app.albums.lo
      http:
        paths:
          - path: "/.*"
            pathType: Prefix
            backend:
              service:
                name: albums-frontend
                port:
                  name: http
          - path: "/api/.*"
            pathType: Prefix
            backend:
              service:
                name: albums-backend
                port:
                  name: http
    - host: neo4j.albums.lo
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: albums-neo4j-db
                port:
                  name: neo4j
