spring:
  neo4j:
    uri: ${NEO4J_DB_URI}
    authentication:
      username: ${NEO4J_DB_USERNAME}
      password: ${NEO4J_DB_PASSWORD}
  webflux:
    base-path: "/api"

rate-limits:
  image-upload:
    limit: ${RATE_LIMIT_IMAGE_UPLOAD_LIMIT}
    refillTimeMs: ${RATE_LIMIT_IMAGE_UPLOAD_REFILL_TIME_MS}

image-service:
  hash-sample-size: ${HASH_SAMPLE_SIZE}
  similarity-threshold: ${SIMILARITY_THRESHOLD}
  thumbnail-size: ${THUMNAIL_SIZE}
  thumbnails-directory: ${THUMBNAILS_DIRECTORY}
  full-image-directory: ${FULL_IMAGE_DIRECTORY}
