spring:
  neo4j:
    uri: ${NEO4J_DB_URI}
    authentication:
      username: ${NEO4J_DB_USERNAME}
      password: ${NEO4J_DB_PASSWORD}
  webflux:
    base-path: "/api"
    cors:
      allowed-origins:
        - ${PUBLIC_ORIGIN}

server:
  http2:
    enabled: true

rate-limits:
  image-upload:
    max-concurrent: ${RATE_LIMIT_IMAGE_UPLOAD_MAX_CONCURRENT}

image-service:
  hash-sample-size: ${HASH_SAMPLE_SIZE}
  similarity-threshold: ${SIMILARITY_THRESHOLD}
  thumbnail-size: ${THUMNAIL_SIZE}
  thumbnails-directory: ${THUMBNAILS_DIRECTORY}
  full-image-directory: ${FULL_IMAGE_DIRECTORY}
