spring:
  neo4j:
    uri: ${NEO4J_DB_URI}
    authentication:
      username: ${NEO4J_DB_USERNAME}
      password: ${NEO4J_DB_PASSWORD}
  webflux:
    base-path: "/api"

image-service:
  hash-sample-size: ${HASH_SAMPLE_SIZE:100}
  similarity-threshold: ${SIMILARITY_THRESHOLD:0.82}
  thumbnail-size: ${THUMNAIL_SIZE:250}
  thumbnails-directory: ${THUMBNAILS_DIRECTORY}
  full-image-directory: ${FULL_IMAGE_DIRECTORY}
