spring:
  neo4j:
    uri: "bolt://localhost:7687"
    authentication:
      username: "neo4j"
      password: "password"
  webflux:
    cors:
      allowed-origins:
        - "http://localhost:4200"

org:
  neo4j:
    migrations:
      database: "neo4j"

image-service:
  thumbnails-directory: "./data/thumbnails"
  full-image-directory: "./data/pictures"

logging:
  level:
    nl.juraji: debug
    org.springframework.web: debug
    org.springframework.context.support: warn
    org.springframework.data.neo4j: debug
