spring:
  neo4j:
    uri: ${NEO4J_DB_URI}
    authentication:
      username: ${NEO4J_DB_USERNAME}
      password: ${NEO4J_DB_PASSWORD}
  webflux:
    base-path: "/api"

org:
  neo4j:
    migrations:
      enabled: true
      database: ${NEO4J_DB_NAME}
      locations-to-scan: "classpath:neo4j/migrations"


image-service:
  hash-sample-size: ${HASH_SAMPLE_SIZE:100}
  similarity-threshold: ${SIMILARITY_THRESHOLD:0.82}
  thumbnail-size: ${THUMNAIL_SIZE:250}
  thumbnails-directory: ${THUMBNAILS_DIRECTORY}
  full-image-directory: ${FULL_IMAGE_DIRECTORY}
