spring:
  neo4j:
    uri: "bolt://localhost:7687"
    authentication:
      username: "neo4j"
      password: "password"
  webflux:
    base-path: "/api"

org:
  neo4j:
    migrations:
      enabled: true
      database: "neo4j"
      locations-to-scan: "classpath:neo4j/migrations"


image-service:
  hash-sample-size: 100
  similarity-threshold: 0.82
  thumbnail-size: 250
  thumbnails-directory: "/data/thumbnails"
  full-image-directory: "/data/pictures"
