backend:
  autoScale:
    maxReplicas: 4
  resources:
    cpu: 1000m
    memory: 1Gi

frontend:
  resources:
    cpu: 250m
    memory: 250Mi

neo4j:
  resources:
    cpu: 500m
    memory: 500Mi
  credentials:
    dbName: "neo4j"
    username: "neo4j"
    password: "secret"

hostVolumePaths:
#  thumbnails: "F:\\Pictures\\Albums\\Thumbnails"
  thumbnails: "/run/desktop/mnt/host/f/Pictures/Albums/Thumbnails"
#  pictures: "F:\\Pictures\\Albums\\Pictures"
  pictures: "/run/desktop/mnt/host/f/Pictures/Albums/Pictures"
#  neo4jData: "F:\\Pictures\\Albums\\DbData"
  neo4jData: "/run/desktop/mnt/host/f/Pictures/Albums/DbData"