backend:
  autoScale:
    minReplicas: 1
    maxReplicas: 6
  resources:
    cpu: 1000m
    memory: 2Gi
  javaOptions:
    - "-Xms512m"
    - "-XX:MaxRAMPercentage=75.0"

frontend:
  resources:
    cpu: 10m
    memory: 50Mi

neo4j:
  resources:
    cpu: 1000m
    memory: 2Gi
  credentials:
    dbName: "neo4j"
    username: "neo4j"
    password: "secret"
  config:
    dbmsMemoryPagecacheSize: 750M
    dbmsMemoryHeapMaxSize: 750M

hostVolumePaths:
  #  thumbnails: "F:\\Pictures\\Albums\\Thumbnails"
  thumbnails: "/run/desktop/mnt/host/f/Pictures/Albums/Thumbnails"
  #  pictures: "F:\\Pictures\\Albums\\Pictures"
  pictures: "/run/desktop/mnt/host/f/Pictures/Albums/Pictures"
  #  neo4jData: "F:\\Pictures\\Albums\\DbData"
  neo4jData: "/run/desktop/mnt/host/f/Pictures/Albums/DbData"