backend:
  autoScale:
    maxReplicas: 8
  resources:
    cpu: 1000m
    memory: 1250Mi

frontend:
  resources:
    cpu: 10m
    memory: 50Mi

neo4j:
  resources:
    cpu: 750m
    memory: 1Gi
  credentials:
    dbName: "neo4j"
    username: "neo4j"
    password: "secret"
  config:
    dbmsMemoryPagecacheSize: 500M
    dbmsMemoryHeapMaxSize: 500M

hostVolumePaths:
#  thumbnails: "F:\\Pictures\\Albums\\Thumbnails"
  thumbnails: "/run/desktop/mnt/host/f/Pictures/Albums/Thumbnails"
#  pictures: "F:\\Pictures\\Albums\\Pictures"
  pictures: "/run/desktop/mnt/host/f/Pictures/Albums/Pictures"
#  neo4jData: "F:\\Pictures\\Albums\\DbData"
  neo4jData: "/run/desktop/mnt/host/f/Pictures/Albums/DbData"